# Generated by Django 6.1 on 2026-08-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignment",
            options={"ordering": ["-created_at"], "verbose_name_plural": "assignments"},
        ),
        migrations.AddField(
            model_name="assignment",
            name="course",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="assignment",
            name="subject_teacher",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="assignment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="due_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
